server:
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: online-store

  sql:
    init:
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

  datasource:
    url: r2dbc:h2:mem:///~/db/online-store;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use-second-level-cache: true
          region:
            factory-class: org.hibernate.cache.jcache.JCacheRegionFactory

