/*
 * Sample API
 * This is a sample API for managing payments and balance. It includes endpoints for making payments and checking the account balance. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.javaprojects.onlinestore.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}